before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/open_hardware_monitor-telegraf-plugin
    binary: open_hardware_monitor-telegraf-plugin
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - 386
      - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^build(?:\([^)]+\))?:'
      - '^chore(?:\([^)]+\))?:'
      - '^ci(?:\([^)]+\))?:'
      - '^docs(?:\([^)]+\))?:'
      - '^refactor(?:\([^)]+\))?:'
      - '^test(?:\([^)]+\))?:'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      386: i386
    format_overrides:
      - goos: windows
        format: zip
    files:
      - etc/*
